language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
# command to install dependencies

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
# command to run tests
script:

  - py.test # or py.test for Python versions 3.5 and below